[package]
name = "flatgeobuf"
version = "0.3.4"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
description = "FlatGeobuf for Rust."
homepage = "https://bjornharrtell.github.io/flatgeobuf/"
repository = "https://github.com/bjornharrtell/flatgeobuf/tree/master/src/rust"
readme = "README.md"
documentation = "https://docs.rs/flatgeobuf/"
license = "ISC"
keywords = ["geo", "r-tree", "spatial"]

[dependencies]
flatbuffers = "0.6"
byteorder = "1.3"
geozero = "0.5.1"
async-trait = "0.1"
reqwest = "0.10"
bytes = "0.5"
log = "0.4"

[dev-dependencies]
geozero-core = "0.5"
rand = "0.7"
hex = "0.4"
criterion = "0.3"
tempfile = "3.1"
tokio = { version = "0.2", default-features = false, features = ["rt-threaded"] }

[[bench]]
name = "read"
harness = false
[[bench]]
name = "geojson"
harness = false
