[package]
name = "flatgeobuf"
version = "0.5.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
description = "FlatGeobuf for Rust."
homepage = "https://flatgeobuf.org/"
repository = "https://github.com/flatgeobuf/flatgeobuf/tree/master/src/rust"
readme = "README.md"
documentation = "https://docs.rs/flatgeobuf/"
license = "BSD-2-Clause"
keywords = ["geo", "r-tree", "spatial"]

[features]
default = ["http"]
http = ["reqwest", "bytes"]

[dependencies]
flatbuffers = "2.0.0"
byteorder = "1.4.2"
geozero = { version = "0.7.0", default-features = false }
# Minimal dependencices without SSL support.
reqwest = { version = "0.11.0", default-features = false, optional = true }
bytes = { version = "1.0.1", optional = true }
log = "0.4.13"
fallible-streaming-iterator = "0.1.9"

[dev-dependencies]
geozero = { version = "0.7.0", default-features = true }
seek_bufread = "1.2"
rand = "0.8.2"
hex = "0.4.2"
criterion = "0.3.3"
tempfile = "3.2.0"
tokio = { version = "1.0.2", default-features = false, features = ["rt-multi-thread"] }
# One test needs SSL support; just use the default system bindings for that.
reqwest = { version = "0.11.0", default-features = true }

[[bench]]
name = "read"
harness = false
[[bench]]
name = "geojson"
harness = false

#[patch.crates-io]
# Patch geozero dependencies (dev only)
#geozero = { path = "../../../../rust/geozero/geozero" }

[package.metadata.docs.rs]
all-features = true

